// FILE PURPOSE: configures Babel, the tool that transforms this project's JS/TS/JSX into
// code React Native's engine (Hermes) can actually run.
//
// `babel-preset-expo` is the default when there's no config at all; it's spelled out here only
// so one extra plugin can be added: `inline-import`, which lets `src/db/migrations/migrations.js`
// (generated by drizzle-kit) `import` the generated `.sql` files as plain strings at build time,
// instead of needing a runtime file-read that wouldn't work on a mobile device. `metro.config.js`
// is the other half of that same feature (it teaches the bundler to recognize `.sql` as a source
// extension in the first place). React Compiler itself is turned on via `app.json`'s
// `experiments.reactCompiler`, not here.
module.exports = function (api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: [['inline-import', { extensions: ['.sql'] }]],
  };
};
