// FILE PURPOSE: configures Metro, the bundler that packages this project's JS/TS/assets into
// the file the app actually loads at runtime. Starts from Expo's own default config and adds
// two project-specific tweaks below.
//
// Learn more https://docs.expo.dev/guides/customizing-metro
const { getDefaultConfig } = require('expo/metro-config');

const config = getDefaultConfig(__dirname);

// Teaches Metro to treat `.sql` files as bundleable source files, not just static assets — this
// is what lets `src/db/migrations/migrations.js` (generated by drizzle-kit) import the raw SQL
// migration files directly. Paired with `babel.config.js`'s `inline-import` plugin, which is
// what actually turns each imported `.sql` file into a plain string at build time.
config.resolver.sourceExts.push('sql');

// Test files live next to the screens they test (e.g. `src/app/categories.test.tsx`), so
// expo-router's file-based routing was sweeping them into the route table and Metro tried to
// bundle them for every platform — `@testing-library/react-native` pulls in Node's `console`
// module, which native bundling can't resolve, breaking `expo export --platform android`. Jest
// finds these files through `jest.config.js`, not this file, so blocking them here only removes
// them from the app bundle / route discovery, never from `npm test`.
config.resolver.blockList = [...config.resolver.blockList, /\.test\.[jt]sx?$/];

module.exports = config;
